INSERT INTO DEPT( DEPT, DEPT_NAME)
SELECT distinct dept , 'DEPT_' || TO_CHAR(DEPT, 'FM00000') FROM item;
--
INSERT INTO USERS (USERNAME, FIRSTNAME, LASTNAME) VALUES('CONSULTING.GCQ@GMAIL.COM', 'GUSTAVO', 'QUEIROZ');
--
INSERT INTO USER_DEPT (USERNAME, DEPT,CREATE_DATE) VALUES('CONSULTING.GCQ@GMAIL.COM', 88,SYSDATE);
INSERT INTO USER_DEPT (USERNAME, DEPT,CREATE_DATE) VALUES('CONSULTING.GCQ@GMAIL.COM', 21,SYSDATE);
--
COMMIT;
